### ISSUE TITLE
Remove duplicated work and add parent to ASF or Maven POM

### ISSUE THREAD

**Issue by slachiewicz** [codehaus-plexus/plexus-pom#157]
We have here duplicated work - maybe will be worth to unify our setup between plexus/mojohous and our ASF Maven projects?

**Comment by slawekjaranowski** [comment]
Yes it is duplicate ... we can merge plexus and mojohause ... but ASF has to many items required by ASF
IMHO some (or most) of plugins from mojohause should be moved to ASF.

**Comment by olamy** [comment]
Please don't! 
Those projects are here because they do not need the same level of bureaucracy as ASF and it's probably better like this...
And btw it could be very very long to check all IP to move it to ASF.

**Comment by slachiewicz** [comment]
Agree that IP can be boring and formality isn't worth effort. 
But only switching base pom to ASF I see only benefits
