### ISSUE TITLE
maven-checkstyle-plugin update to 3.1.1 broke site generation

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-pom#33]
Hi,

The update of maven-checkstyle-plugin from 3.0.0 to 3.1.1 broke the site generation (at least for plexus-archiver).

**Comment by michael-o** [comment]
Which error?

**Comment by plamentotev** [comment]
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-site) on project plexus-archiver: Error generating maven-checkstyle-plugin:3.1.1:checkstyle report: Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'cacheFile' does not exist, please check the documentation -> [Help 1]

Looks like the Checkstyle configuration is not compatible with the plugin new version.

**Comment by slachiewicz** [comment]
maven-shared-resources version 3 is prepared for a new plugin/checkstyle update
